import Header from "@/components/Header";
import "./globals.css";
import { Lato } from "next/font/google";
import Footer from "@/components/Footer";

const lato = Lato({
  weight: ["300", "400", "700"],
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${lato.className} font-sans`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
